# Generated by Django 4.0.5 on 2022-08-05 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Meme_Img', models.ImageField(upload_to='./static/images')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
